# -*- coding: utf-8 -*-
"""finance_complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUq1BkDY0gKqSmz_2Ib7IMYNdARVHVfl

# 開始
"""

#!pip install yfinance
import yfinance as yf

def showincomestmt(name):
  stock = yf.Ticker(name)
  display(stock.get_incomestmt()[::-1])
def showincome(name):
  stock = yf.Ticker(name)
  a = stock.get_incomestmt().to_csv().split("\n")
  print(a[0][1:])
  for i in a:
    if i[0:10]=="NetIncome,":
      print(i)
      break

def str2day(s):
  #s='2024-07-03'
  s=[int(i) for i in s.split("-")]
  s=s[0]*365+s[1]*30.42+s[2]
  return s
def day2str(s):
  #s = 738975.94
  y = int(s//365)
  m = int((s-y*365)//30.42)
  d = round(s-y*365-m*30.42)
  #d = round((s-y*365-m*30.42)*10)/10
  return "%d-%02d-%02d"%(y,m,d)

def average(name):
  a = yf.download(name,period='max',interval='1d')
  a = a.to_csv().split("\n")
  h = a[0]
  a = a[1:-1]
  a = [i.split(",") for i in a]
  b = [[i[0],(float(i[1])+float(i[4]))/2] for i in a]
  return b

def fin(f): #day
  print(f)
  c = []
  for i in range(0,len(b),f):
    if i+f-1>=len(b): break
    v = 0
    for j in range(f):
        v += b[i+j][1]
    c.append([b[i][0],b[i+f-1][0],v])
  d = []
  for i in range(1,len(c),1):
    #d.append([[c[i-1][0],c[i-1][1]],[c[i][0],c[i][1]],(c[i][2]-c[i-1][2])/f])
    d.append([[c[i-1][0],c[i][0],c[i][1]],(c[i][2]-c[i-1][2])/f])
  e = []
  for i in range(1,len(d),1):
    e.append(d[i][1])
  for i in d[-6:]:
    ss = [str2day(j) for j in i[0]]
    #sss = [day2str(j) for j in [ss[1]-ss[0], ss[2]-ss[1], (ss[2]-ss[0])]]
    sss = day2str((ss[2]-ss[0])/2)
    print(i[0],sss,i[1],sep=" ")
  print()

name = '2330.TW'
b = average(name)

#showincomestmt(name)
showincome(name)

fin(1)
fin(7)
fin(30)
fin(365)
fin(365*2)
fin(365*3)
fin(365*10)